package com.fndong.user;
// Generated Mar 11, 2016 2:47:24 PM by Hibernate Tools 4.3.1.Final

/**
 * UserDetails generated by hbm2java
 */
public class UserDetails implements java.io.Serializable {

	private Integer userDetailId;
	private User user;
	private String address;
	private String poscode;

	public UserDetails() {
	}

	public UserDetails(User user) {
		this.user = user;
	}

	public UserDetails(User user, String address, String poscode) {
		this.user = user;
		this.address = address;
		this.poscode = poscode;
	}

	public Integer getUserDetailId() {
		return this.userDetailId;
	}

	public void setUserDetailId(Integer userDetailId) {
		this.userDetailId = userDetailId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPoscode() {
		return this.poscode;
	}

	public void setPoscode(String poscode) {
		this.poscode = poscode;
	}

}
