package com.fndong.user;
// Generated Mar 11, 2016 2:47:24 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String password;
	private String name;
	private String email;
	private UserDetails userDetails;

	public User() {
	}

	public User(String password, String name, String email) {
		this.password = password;
		this.name = name;
		this.email = email;
	}

	public User(String password, String name, String email, UserDetails userDetails) {
		this.password = password;
		this.name = name;
		this.email = email;
		this.userDetails = userDetails;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

}
